export interface ExerciseFromApiFirebase {
    description: string,
    difficulty: string,
    equipment:string[],
    frequency: number,
    id: number,
    image: string,
    instructions: string[],
    kcalBurned: string,
    mainAreas: string[],
    maxRep: number,
    minRep: number,
    name: string,
    objective: string,
    precautions:string,
    secondAreas: string[],
    series: number,
    video:string,
    creationDate?: string
}

export interface Exercise {
    description: string,
    difficulty: 'Principiante' | 'Intermedio' | 'Avanzado',
    equipment:string[],
    frequency: number,
    id: number,
    image: string,
    instructions: string[],
    kcalBurned: string,
    mainAreas: string[],
    maxRep: number,
    minRep: number,
    name: string,
    objective: string,
    precautions:string,
    secondAreas: string[],
    series: number,
    video:string,
    creationDate?: string
}
